apiVersion: v1
kind: Pod
metadata:
  name: crashloop-demo
  labels:
    scenario: "05-crashloop-cmd"
    app: crashloop-demo
spec:
  containers:
    - name: app
      image: busybox:stable
      command: ["sh", "-c", "echo 'Starting up...' && sleep 2 && echo 'Crashing now!' && exit 1"]
      resources:
        requests:
          memory: "16Mi"
          cpu: "10m"
        limits:
          memory: "32Mi"
          cpu: "50m"
  restartPolicy: Always
